import { FaGraduationCap, FaQuoteLeft, FaTasks, FaGithub, FaLinkedin, FaBriefcase, FaDownload, FaMapPin, FaMailBulk, FaArrowUp, FaArrowDown, FaPaperPlane, FaExternalLinkAlt } from "react-icons/fa";
import { MdMonitor, MdSpeed, MdDesignServices, MdInsights, MdSearch, MdPeople, MdAccountTree, MdTimeline, MdCallSplit, MdBarChart, MdLowPriority, MdGridView, MdWidgets, MdAccessibility, MdSecurity, MdTrendingUp, MdSchema, MdFactCheck } from "react-icons/md";

export const GraduationCap = FaGraduationCap;
export const Quote = FaQuoteLeft;
export const Kanban = FaTasks;
export const Github = FaGithub;
export const Linkedin = FaLinkedin;
export const Briefcase = FaBriefcase;
export const Download = FaDownload;
export const MapPin = FaMapPin;
export const Mail = FaMailBulk;
export const ArrowUp = FaArrowUp;
export const ArrowDown = FaArrowDown;
export const Send = FaPaperPlane;
export const ExternalLink = FaExternalLinkAlt;

export const Monitor = MdMonitor;
export const Speed = MdSpeed;
export const DesignServices = MdDesignServices;
export const Insights = MdInsights;
export const Search = MdSearch;
export const People = MdPeople;
export const Blueprint = MdAccountTree;
export const Journey = MdTimeline;
export const Flow = MdCallSplit;
export const Kpi = MdBarChart;
export const Priority = MdLowPriority;
export const Wireframe = MdGridView;
export const Prototype = MdWidgets;
export const Accessibility = MdAccessibility;
export const Security = MdSecurity;
export const TrendingUp = MdTrendingUp;
export const Schema = MdSchema;
export const AuditCheck = MdFactCheck;
